import React from "react";
import { TableBlock } from "../components/runtime/TableBlock";
import { MethodButton } from "../components/MethodButton";

const Reservation: React.FC = () => {
  return (
    <div id="page-reservation-1">
    <div id="idl1zd" style={{"display": "flex", "height": "100vh", "fontFamily": "Arial, sans-serif", "--chart-color-palette": "default"}}>
      <nav id="ij66ja" style={{"width": "250px", "background": "linear-gradient(135deg, #4b3c82 0%, #5a3d91 100%)", "color": "white", "padding": "20px", "overflowY": "auto", "display": "flex", "flexDirection": "column", "--chart-color-palette": "default"}}>
        <h2 id="i4ee3s" style={{"marginTop": "0", "fontSize": "24px", "marginBottom": "30px", "fontWeight": "bold", "--chart-color-palette": "default"}}>{"BESSER"}</h2>
        <div id="iv6cae" style={{"display": "flex", "flexDirection": "column", "flex": "1", "--chart-color-palette": "default"}}>
          <a id="i7vlc8" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/gestionnaire">{"Gestionnaire"}</a>
          <a id="icl506" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "rgba(255,255,255,0.2)", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/reservation">{"Reservation"}</a>
          <a id="iii48b" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/centredecongres">{"CentreDeCongres"}</a>
          <a id="i3941j" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/paiement">{"Paiement"}</a>
          <a id="iw9in6" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/evenement">{"Evenement"}</a>
          <a id="iboj77" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/elementcentre">{"ElementCentre"}</a>
          <a id="i0m8wg" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/materiel">{"Materiel"}</a>
          <a id="ibsa56" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/prestation">{"Prestation"}</a>
          <a id="ihgpq2" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/personnereferente">{"PersonneReferente"}</a>
          <a id="im1lsy" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/tarif">{"Tarif"}</a>
          <a id="iyuxe6" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/indisponibilte">{"Indisponibilte"}</a>
          <a id="irhqk1" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/contraintes">{"Contraintes"}</a>
          <a id="ij5jn4" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/reglelocation">{"RegleLocation"}</a>
        </div>
        <p id="iw8tqg" style={{"marginTop": "auto", "paddingTop": "20px", "borderTop": "1px solid rgba(255,255,255,0.2)", "fontSize": "11px", "opacity": "0.8", "textAlign": "center", "--chart-color-palette": "default"}}>{"© 2026 BESSER. All rights reserved."}</p>
      </nav>
      <main id="ivh8zq" style={{"flex": "1", "padding": "40px", "overflowY": "auto", "background": "#f5f5f5", "--chart-color-palette": "default"}}>
        <h1 id="iexnq6" style={{"marginTop": "0", "color": "#333", "fontSize": "32px", "marginBottom": "10px", "--chart-color-palette": "default"}}>{"Reservation"}</h1>
        <p id="igrr64" style={{"color": "#666", "marginBottom": "30px", "--chart-color-palette": "default"}}>{"Manage Reservation data"}</p>
        <TableBlock id="table-reservation-1" styles={{"width": "100%", "minHeight": "400px", "--chart-color-palette": "default"}} title="Reservation List" options={{"showHeader": true, "stripedRows": false, "showPagination": true, "rowsPerPage": 5, "actionButtons": true, "columns": [{"label": "DateCreation", "column_type": "field", "field": "dateCreation", "type": "date", "required": true}, {"label": "DateDebut", "column_type": "field", "field": "dateDebut", "type": "date", "required": true}, {"label": "DateFin", "column_type": "field", "field": "dateFin", "type": "date", "required": true}, {"label": "DelaiDeConfirmation", "column_type": "field", "field": "delaiDeConfirmation", "type": "int", "required": true}, {"label": "CoutTotal", "column_type": "field", "field": "coutTotal", "type": "float", "required": true}, {"label": "Statut", "column_type": "field", "field": "Statut", "type": "enum", "options": ["ANNULEE", "CONFIRMEE", "EN_ATTENTE", "EXPIREE", "MODIFIEE"], "required": true}], "formColumns": [{"column_type": "field", "field": "dateCreation", "label": "dateCreation", "type": "date", "required": true, "defaultValue": null}, {"column_type": "field", "field": "dateDebut", "label": "dateDebut", "type": "date", "required": true, "defaultValue": null}, {"column_type": "field", "field": "dateFin", "label": "dateFin", "type": "date", "required": true, "defaultValue": null}, {"column_type": "field", "field": "delaiDeConfirmation", "label": "delaiDeConfirmation", "type": "int", "required": true, "defaultValue": null}, {"column_type": "field", "field": "coutTotal", "label": "coutTotal", "type": "float", "required": true, "defaultValue": null}, {"column_type": "field", "field": "Statut", "label": "Statut", "type": "enum", "required": true, "defaultValue": null, "options": ["ANNULEE", "CONFIRMEE", "EN_ATTENTE", "EXPIREE", "MODIFIEE"]}, {"column_type": "lookup", "path": "paiement", "field": "paiement", "lookup_field": "montant", "entity": "Paiement", "type": "str", "required": false}, {"column_type": "lookup", "path": "evenement", "field": "evenement", "lookup_field": "nom", "entity": "Evenement", "type": "str", "required": true}, {"column_type": "lookup", "path": "elementcentre", "field": "elementcentre", "lookup_field": "nom", "entity": "ElementCentre", "type": "list", "required": true}, {"column_type": "lookup", "path": "tarif", "field": "tarif", "lookup_field": "saison", "entity": "Tarif", "type": "str", "required": true}, {"column_type": "lookup", "path": "materiel", "field": "materiel", "lookup_field": "nom", "entity": "Materiel", "type": "list", "required": false}, {"column_type": "lookup", "path": "prestation", "field": "prestation", "lookup_field": "nom", "entity": "Prestation", "type": "list", "required": false}]}} dataBinding={{"entity": "Reservation", "endpoint": "/reservation/"}} />
        <div id="il78hu" style={{"marginTop": "20px", "display": "flex", "gap": "10px", "flexWrap": "wrap", "--chart-color-palette": "default"}}>
          <MethodButton id="iz9uhc" className="action-button-component" style={{"display": "inline-flex", "alignItems": "center", "padding": "6px 14px", "background": "linear-gradient(90deg, #2563eb 0%, #1e40af 100%)", "color": "#fff", "textDecoration": "none", "borderRadius": "4px", "fontSize": "13px", "fontWeight": "600", "letterSpacing": "0.01em", "cursor": "pointer", "border": "none", "boxShadow": "0 1px 4px rgba(37,99,235,0.10)", "transition": "background 0.2s", "--chart-color-palette": "default"}} endpoint="/reservation/{reservation_id}/methods/modifier/" label="modifier" isInstanceMethod={true} instanceSourceTableId="table-reservation-1" />
          <MethodButton id="ihijza" className="action-button-component" style={{"display": "inline-flex", "alignItems": "center", "padding": "6px 14px", "background": "linear-gradient(90deg, #2563eb 0%, #1e40af 100%)", "color": "#fff", "textDecoration": "none", "borderRadius": "4px", "fontSize": "13px", "fontWeight": "600", "letterSpacing": "0.01em", "cursor": "pointer", "border": "none", "boxShadow": "0 1px 4px rgba(37,99,235,0.10)", "transition": "background 0.2s", "--chart-color-palette": "default"}} endpoint="/reservation/{reservation_id}/methods/annuler/" label="annuler" isInstanceMethod={true} instanceSourceTableId="table-reservation-1" />
          <MethodButton id="i5e8w4" className="action-button-component" style={{"display": "inline-flex", "alignItems": "center", "padding": "6px 14px", "background": "linear-gradient(90deg, #2563eb 0%, #1e40af 100%)", "color": "#fff", "textDecoration": "none", "borderRadius": "4px", "fontSize": "13px", "fontWeight": "600", "letterSpacing": "0.01em", "cursor": "pointer", "border": "none", "boxShadow": "0 1px 4px rgba(37,99,235,0.10)", "transition": "background 0.2s", "--chart-color-palette": "default"}} endpoint="/reservation/{reservation_id}/methods/calculerCout/" label="calculerCout" isInstanceMethod={true} instanceSourceTableId="table-reservation-1" />
          <MethodButton id="ir25lh" className="action-button-component" style={{"display": "inline-flex", "alignItems": "center", "padding": "6px 14px", "background": "linear-gradient(90deg, #2563eb 0%, #1e40af 100%)", "color": "#fff", "textDecoration": "none", "borderRadius": "4px", "fontSize": "13px", "fontWeight": "600", "letterSpacing": "0.01em", "cursor": "pointer", "border": "none", "boxShadow": "0 1px 4px rgba(37,99,235,0.10)", "transition": "background 0.2s", "--chart-color-palette": "default"}} endpoint="/reservation/{reservation_id}/methods/confirmer/" label="confirmer" isInstanceMethod={true} instanceSourceTableId="table-reservation-1" />
        </div>
      </main>
    </div>    </div>
  );
};

export default Reservation;
